[package]
name = "dewars_protobufs"
edition = "2021"
version = "0.3.25"
description = "DEWARS Protobuf definitions"
repository = "https://github.com/DEWARS-org/protobufs"
license-file = "LICENSE"
include = [
    "**/*.rs",
    "Cargo.toml",
]

[dependencies]
prost = "0.13.3"
prost-types = "0.13.3"
