name: CI

on: push

permissions: write-all

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code & submodules
        uses: actions/checkout@v4
      - name: Setup Buf
        uses: bufbuild/buf-setup-action@main
        with:
          github_token: ${{ github.token }}
      - name: install protoc-gen-es
        run: npm install -g @bufbuild/protoc-gen-es
      - name: Generate code
        run: buf generate dewars
      - name: Copy license
        run: cp LICENSE packages/ts && cp LICENSE packages/rust
      - name: Upload Rust code
        uses: actions/upload-artifact@v4
        with:
          name: rust_code
          path: packages/rust
      - name: Upload TypeScript code
        uses: actions/upload-artifact@v4
        with:
          name: ts_code
          path: packages/ts

  publish-jsr:
    runs-on: ubuntu-latest
    needs: codegen
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download TypeScript code
        uses: actions/download-artifact@v4
        with:
          name: ts_code
      - name: Publish to JSR
        run: npx jsr publish --unstable-sloppy-imports

  publish-cargo:
    runs-on: ubuntu-latest
    needs: codegen
    steps:
      - name: Download Rust code
        uses: actions/download-artifact@v4
        with:
          name: rust_code
