name: CI

on: push

permissions: write-all

jobs:
  codegen:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code & submodules
        uses: actions/checkout@v4
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: install dependencies
        run: deno task install
      - name: Generate code
        run: deno task generate
      - name: Copy license
        run: cp LICENSE packages/ts && cp LICENSE packages/rust
      - name: Upload Rust code
        uses: actions/upload-artifact@v4
        with:
          name: rust-code
          path: packages/rust
      - name: Upload TypeScript code
        uses: actions/upload-artifact@v4
        with:
          name: ts-code

  publish-jsr:
    runs-on: ubuntu-latest
    needs: codegen
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Download TypeScript code
        uses: actions/download-artifact@v4
        with:
          name: ts-code
      - name: Publish to JSR
        run: npx jsr publish

  publish-cargo:
    runs-on: ubuntu-latest
    needs: codegen
    steps:
      - name: Download Rust code
        uses: actions/download-artifact@v4
        with:
          name: rust-code
